### ISSUE TITLE
Broken SSE2 graphic functions

### ISSUE THREAD

**Issue by uyjulian** [uyjulian/krkrsdl2#14]
Currently, `TVPInterpStretchCopy_sse2_c` is broken (results in "blocky" image).

Currently, to work around this, use `-cpusse2=no` command line argument.

**Comment by uyjulian** [comment]
I isolated the graphical issues to `TVPInterpStretchCopy_sse2_c` and `TVPConvert24BitTo32Bit_ssse3_c`, so I disabled those for now.

**Comment by 3c1u** [comment]
Since the weird glitch appears in every 4-pixels row, the shuffling can eliminate it. I am not quite sure what causes this.

https://twitter.com/murueka_misw/status/1298345382842261504

**Comment by uyjulian** [comment]
I guess the ordering of `__m128i` may change. I'm going to fix this by replacing `_mm_store_si128` with `memcpy`

**Comment by uyjulian** [comment]
Fixed. Looks like I messed up the ordering when I changed the MSVC/ICC-specific member access to intrinsics…

**Comment by uyjulian** [comment]
As for why I didn't catch this the first time around, it's most likely because I deleted the processor flags along with the optimization flags when testing.
