### ISSUE TITLE
Script exception raised Member "WIN32Dialog" does not exist

### ISSUE THREAD

**Issue by Neko-Monika** [uyjulian/krkrsdl2#21]
I'm trying to launch English version of visual novel "Sanoba Witch" for testing purposes; first of all I decompiled data.xp3 and then started krkrsdl2 from the Terminal. But eventually I got an «Member "WIN32Dialog" does not exist» error and game hadn't start.

I'm using macOS 10.15.6 Catalina.
![Снимок экрана 2020-09-10 в 23 41 05](https://user-images.githubusercontent.com/29918546/92767469-5647b880-f3c1-11ea-8ef7-8425ba2d4d32.png)

**Comment by uyjulian** [comment]
That feature won't ever be supported by this program as it relies on Windows specific APIs.

Instead, use Crossover 19 to run the program (it is supported by Catalina)
