### ISSUE TITLE
The example of kag3 just shows only one character

### ISSUE THREAD

**Issue by Yamilemon** [uyjulian/krkrsdl2#24]
I used this example(https://github.com/uyjulian/kag3) and compiled it successfully.

But it only shows one character on the browser, This character is "こ".

I used emscripten to compile. The same problem is that I only see one character on this page:https://ghpages.uyjulian.pw/krkrsdl2/

What is the problem and how should I solve it?

**Comment by Yamilemon** [comment]
I started a service and you can try it : http://149.28.21.205:3004/index.html

**Comment by uyjulian** [comment]
Web browser changes broke `Timer`.  

I'll fix it later

**Comment by Yamilemon** [comment]
> Web browser changes broke `Timer`.
> 
> I'll fix it later



> Web browser changes broke `Timer`.
> 
> I'll fix it later

Oh, if timer doesn't work, most of kag's functions won't work. This may be a big problem.

**Comment by Yamilemon** [comment]
> Web browser changes broke `Timer`.
> 
> I'll fix it later

Oh, if timer doesn't work, most of kag's functions won't work. This may be a big problem.

**Comment by choryuidentify** [comment]
I tried build it to my Ubuntu 18.04 VM (It's native build, not Browser.) and only shows "こ" too.

So, I manually edit 'scenario/first.ks'. Insert Japanese sentence into bottom, and it works.

But first line are not displaying until next line invoked.

![krkr1](https://user-images.githubusercontent.com/14815572/100372390-8449aa00-304c-11eb-93ca-7114c3272f2e.gif)

**Comment by uyjulian** [comment]
Worked around by 0ee08afb4273d2846b37b42f0026693b1fa4bc37
