### ISSUE TITLE
Cannot read and save files on the browser

### ISSUE THREAD

**Issue by Yamilemon** [uyjulian/krkrsdl2#36]
I used the web version of release: https://github.com/uyjulian/krkrsdl2/releases.
And then I used this kag3: https://github.com/uyjulian/kag3

**I wanted to show a picture, so I modified it first.ks file :**

[wait time=200]
*start|スタート
@cm
@layopt layer=message0 visible=false
[backlay]
[image storage="bg.jpg" layer=base page=back visible=true]
[trans method=crossfade time=500]
[wt]

**Finally, I packaged it into an XP3 file and ran it on a browser.**

**The browser displays an error:**

14:58:17 trace : animationlayer.tjs(483)[(function) loadImages] <-- graphiclayer.tjs(66)[(function) loadImages] <-- graphiclayer.tjs(368)[(function) loadImages] <-- mainwindow.tjs(5408)[(function expression) (anonymous)] <-- conductor.tjs(440)[(function) onTag] <-- conductor.tjs(104)[(function) timerCallback]
14:58:17 エラーが発生しました
ファイル : first.ks   行 : 6
タグ : image ( ← エラーの発生した前後のタグを示している場合もあります )
Cannot open storage file://./data/data.xp3>bg.jpg

**I guess it maybe unable to read the file? 
Then I have a question, the web version may not be able to save the file too, because it is running on the browser, can not operate the local file, right? As a result, it may not be able to archive locally.**

**Comment by uyjulian** [comment]
You need to package the file into the archive.

**Comment by uyjulian** [comment]
If this is still an issue, please reopen.

**Comment by Yamilemon** [comment]
But, how can I read or write a file through tjs on the web version? Is there any way to pass data between tjs and javascript on the browser? I'm not very good at C++, so I don't know how to use Emscripten FS API.

**Comment by Yamilemon** [comment]
> If this is still an issue, please reopen.

But, how can I read or write a file through tjs on the web version? Is there any way to pass data between tjs and javascript on the browser? I'm not very good at C++, so I don't know how to use Emscripten FS API.

**Comment by uyjulian** [comment]
Passing data between TJS and JS is done using using `KirikiriEmscriptenInterface`.  
Some sample usages are here: https://gist.github.com/uyjulian/b9d41c776112eb4a919bcb6893ed0174

The Emscripten FS API is in Javascript. https://emscripten.org/docs/api_reference/Filesystem-API.html

**Comment by Yamilemon** [comment]
Thank you. I think I can pass the data from TJS to JS through the interface, and then I can save the data on the server.
