### ISSUE TITLE
Couldn't find libSDL2.so on android-project

### ISSUE THREAD

**Issue by Yamilemon** [uyjulian/krkrsdl2#38]
I opened the android-project with Android Studio. According to AndroidManifest.xml, I created an Activity to extends SDLActivity.

I built it and ran it on my Android phone, However, there was an error in the application like this: 

W/System.err: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.libsdl.app-1/base.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.libsdl.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.libsdl.app-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libSDL2.so"

Is there any binary file missing?

**Comment by uyjulian** [comment]
Fixed. There was a mistake in the build process
